.PHONY: clean All

All:
	@echo "----------Building project:[ UnderstandingPointers - Debug ]----------"
	@cd "UnderstandingPointers" && "$(MAKE)" -f  "UnderstandingPointers.mk"
clean:
	@echo "----------Cleaning project:[ UnderstandingPointers - Debug ]----------"
	@cd "UnderstandingPointers" && "$(MAKE)" -f  "UnderstandingPointers.mk" clean
