.PHONY: clean All

All:
	@echo "----------Building project:[ Class_Challenge - Debug ]----------"
	@cd "Class_Challenge" && "$(MAKE)" -f  "Class_Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Class_Challenge - Debug ]----------"
	@cd "Class_Challenge" && "$(MAKE)" -f  "Class_Challenge.mk" clean
